### ISSUE TITLE
Road paving does not offset in front of car relative to car rotation

### ISSUE THREAD

**Issue by mileslef** [binaryreveries/FollowMe#2]
Currently newRoad is instantiated with the same position and rotation as the player. ideally we would have the newRoad instantiated in front of the player at distance defined by roadPush. The current solution is to add road Push to the y axis, which only works when the player is driving directly north.

This might not be someone that we want to implement, in which case we should remove roadPush and newPosition.

**Comment by davisjc** [comment]
Much better!
